CREATE TABLE CLIENTE(
	ID INTEGER PRIMARY KEY
	NOT NULL DEFAULT '-1',
	NOME VARCHAR(50) NOT NULL 
	DEFAULT 'UNDEFINED',
	IDADE INTEGER NOT NULL DEFAULT -1,	
);


SELECT * FROM CLIENTE; /*/
INSERT INTO CLIENTE VALUES(1,'teste',20);


